language: node_js
node_js:
  - "stable"
before_install:
  - "cd .."
  - "git clone https://github.com/alekpentchev/node-shopping-cart-api.git"
  - "cd node-shopping-cart-api"
  - "npm i"
  - "npm run start &" 
  - "cd ../react-shopping-cart"